sentry:
  dsn: "https://502f25099c204a2fbf4cb16edc5975d1@o447951.ingest.sentry.io/5428563"
  in-app-includes: "com.example.demo"
  max-breadcrumbs: 150
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: debug
  enable-tracing: true
  traces-sample-rate: 1.0